
#version: 1.0.{build}-{branch}
version: "{build}-{branch}"

environment:
  matrix:
    #- RUBY_VERSION: 193
    #  TZONE: "UTC"
    #- RUBY_VERSION: 193
    #  TZONE: "Tokyo Standard Time"
    #- RUBY_VERSION: 193
    #  TZONE: "Eastern Standard Time"
    - RUBY_VERSION: 24
      TZONE: "UTC"
      GEMFILE: Gemfile.appveyor_tzi125
    - RUBY_VERSION: 24
      TZONE: "Tokyo Standard Time"
      GEMFILE: Gemfile.appveyor_tzi125
    - RUBY_VERSION: 24
      TZONE: "Eastern Standard Time"
      GEMFILE: Gemfile.appveyor_tzi125
    - RUBY_VERSION: 24
      TZONE: "UTC"
      GEMFILE: Gemfile.appveyor
    - RUBY_VERSION: 24
      TZONE: "Tokyo Standard Time"
      GEMFILE: Gemfile.appveyor
    - RUBY_VERSION: 24
      TZONE: "Eastern Standard Time"
      GEMFILE: Gemfile.appveyor

install:
  - tzutil /g
  - echo %RUBY_VERSION%
  - echo %TZONE%
  - tzutil /s "%TZONE%"
  - tzutil /g
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - cp "%GEMFILE%" Gemfile
  - bundle install

build: off

before_test:
  - ruby -v
  - ruby -e "p [ ENV['TZ'], Time.now, Time.now.zone ]"
  - gem -v
  - bundle -v
  - bundle list

test_script:
  - bundle exec rspec

notifications:
- provider: Email
  to:
    - jmettraux+appveyor@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

