
#version: 1.0.{build}-{branch}
version: "{build}-{branch}"

environment:
  matrix:
    #- RUBY_VERSION: 193
    #  TZONE: "UTC"
    #- RUBY_VERSION: 193
    #  TZONE: "Tokyo Standard Time"
    #- RUBY_VERSION: 193
    #  TZONE: "Eastern Standard Time"
    - RUBY_VERSION: 25
      TZONE: "UTC"
      GEMFILE: Gemfile.appveyor_tzi125
    - RUBY_VERSION: 25
      TZONE: "Tokyo Standard Time"
      GEMFILE: Gemfile.appveyor_tzi125
    - RUBY_VERSION: 25
      TZONE: "Eastern Standard Time"
      GEMFILE: Gemfile.appveyor_tzi125
    - RUBY_VERSION: 25
      TZONE: "UTC"
      GEMFILE: Gemfile.appveyor
    - RUBY_VERSION: 25
      TZONE: "Tokyo Standard Time"
      GEMFILE: Gemfile.appveyor
    - RUBY_VERSION: 25
      TZONE: "Eastern Standard Time"
      GEMFILE: Gemfile.appveyor

install:
  - tzutil /g
  - echo %RUBY_VERSION%
  - echo %TZONE%
  - tzutil /s "%TZONE%"
  - tzutil /g
  #- setx TZ "%TZ%"
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - cp "%GEMFILE%" Gemfile
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - bundle list
  - ruby -e "n = Time.now; p [ ENV['TZ'], n, n.zone, n.strftime('%z %Z') ]"
  - bundle exec ruby -e "require 'et-orbi'; p EtOrbi.determine_local_tzone"

test_script:
  - bundle exec rspec

notifications:
- provider: Email
  to:
    - jmettraux+appveyor@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

