
#version: 1.0.{build}-{branch}
version: "{build}-{branch}"

environment:
  matrix:
    - RUBY_VERSION: 193
      TZONE: "UTC"
    - RUBY_VERSION: 24
      TZONE: "UTC"
    - RUBY_VERSION: 193
      TZONE: "Tokyo Standard Time"
    - RUBY_VERSION: 24
      TZONE: "Tokyo Standard Time"
    - RUBY_VERSION: 193
      TZONE: "Eastern Standard Time"
    - RUBY_VERSION: 24
      TZONE: "Eastern Standard Time"

install:
  - echo %RUBY_VERSION%
  - echo %TZONE%
  - tzutil /s "%TZONE%"
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - cp Gemfile.appveyor Gemfile
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rspec

notifications:
- provider: Email
  to:
    - jmettraux+flor@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

