
language: ruby

rvm:
  #- 1.8.7 # no, since it doesn't get fun(a, *b, c) or fun0\n.fun1
  #- 1.9.3 # Travis broken September 2017
  #- ruby-1.9.3-p551
  #- 2.1.1
  #- 2.2.2 # removed 2018-01-05
  - 2.3.1
  - 2.4.1
  - 2.5.3
  - 2.6.0
  #- jruby-19mode # Travis broken September 2017
  #- jruby-20mode # Travis broken September 2017
  - jruby-9.1.13.0

#matrix:
#  include:
#    - rvm: jruby-9.1.13.0

#before_install: gem install bundler
script: bundle exec rspec
branches:
  only:
    - master
  #except:
  #  - master

sudo: false
cache: bundler

env:
  - ""
  - TZ=UTC
  - TZ=Asia/Tokyo
  - TZ=America/Chicago

